### ISSUE TITLE
Port to C#

### ISSUE THREAD

**Issue by bhandziuk** [apearson/southern-company-api#142]
I'm working on porting much of the code you've written to C#. 

I have the authentication process working. It's a little different from the code here I think in that, for me, `https://customerservice2.southerncompany.com/Account/LoginValidated/JwtToken` was giving me 404. But I found that a usable `ScJwtToken` is in the `https://customerservice2.southerncompany.com/Account/LoginComplete?ReturnUrl=/billing/home` result anyway. I also changed the `ReturnUrl` from `null` to any string. It's ignored but required. 

I also have the hourly data api working (that's what I was most interested in). I was pleased to see that I can get all the hourly data more than 2 years back. It only shows 2 years on the GA Power website. 

Thank you so much for this project! It was immensely helpful!.

My repo is here [UtilityTracking](https://github.com/bhandziuk/UtilityTracking).

**Comment by apearson** [comment]
I'm glad my code was readable, portable, and helpful! 

Just a note (at least for Alabama Power), when you go on a special plan (time of use, ev rate rider, etc) they seem to remove the hourly data.
