### ISSUE TITLE
obtaining ScJwtToken

### ISSUE THREAD

**Issue by chadamodio** [apearson/southern-company-api#17]
Hello, thank you for this repo! 
I am not receiving all cookies during the last authentication step and only receiving dtCookie. Have you seen this before? any tips?

**Comment by apearson** [comment]
I'll check into this and let you know

**Comment by apearson** [comment]
Couple of questions:

1. What company is your account from

Is the library throwing any errors?  Do you have any logs?

**Comment by chadamodio** [comment]
Sorry, to be clear, I got it working in node, running into the issue in python. 
Would you have any guidance there? I know this isn't the proper place for the question but there is no other way to reach out to you. Thanks again, either way.

**Comment by apearson** [comment]
No worries, the more libraries the better.  

Just to get it out of the way, this is an unofficial API and is derived from how the website gets it data. 

Do you have any source code?  Normally if you aren't getting the correct cookie then the server isn't receiving the correct data or you're posting to the wrong url.  

The auth code was updated a couple months ago but I'm not sure if the readme's explanation has been updated to match.

**Comment by chadamodio** [comment]
Also just for awareness, I am looking to obtain the https://customerservice2api.southerncompany.com/api/Billing/getAllBills data as my client oversees and pays for a whole apartment building. If I get it working properly for node, I will fork your repo and add it for your approval.

As for python, I will clean up the code and get it posted publicly, then share it with you. It will be a single script though, not a python library at this time. 

PS: just FYI, in your readme URL `/LogginValidated/JwtToken`
 has a typo with too many g's.

**Comment by apearson** [comment]
Sounds good! 

I've been testing and it looks like that url should just work once you get the Authorization header with the JWT in place.   This should be pretty easy to integrate into the current library, just never ran into that url in my web interface.  Thank you :) 

Thanks for the heads up.  The readme was actually correct but SoCo corrected their API typo and I corrected the typo in the code just not the readme.

**Comment by chadamodio** [comment]
Yeah I just got it working, but in my case it is a lot of data so I may leave the function call commented out in main.js. I also added a line to download the json which is what i need. 
I will try to fork your repo tonight and add it. Thanks again.

**Comment by apearson** [comment]
Merged PR! Thanks!
