### ISSUE TITLE
Getting 404 on MonthlyGraph API call

### ISSUE THREAD

**Issue by ehanft** [apearson/southern-company-api#18]
UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://customerservice2api.southerncompany.com/api/MyPowerUsage/MonthlyGraph reason: Unexpected end of JSON input

**Comment by apearson** [comment]
Looking into this now, thanks for letting me know

**Comment by apearson** [comment]
Seems like SoCo updated the request from a POST to a GET.  I'll work on a fix but it might be a little bit before this is pushed

**Comment by ehanft** [comment]
Not a problem. Thanks for the quick response!

**Comment by apearson** [comment]
This issue should be fixed and pushed to npm now.  Let me know if you still have trouble
