### ISSUE TITLE
Volunteering to help with GA power testing

### ISSUE THREAD

**Issue by taboc741** [apearson/southern-company-api#37]
you asked for issue tickets if someone was willing to help test a southern company API.  I'm hopeful GA power is on the list to be able to test against.

**Comment by apearson** [comment]
Hey! 

Yes, I'm looking for help to determine if the daily power api is still working or not.  

If you would like to test then you'll need to: 
- clone the repo
- `npm install`
- uncomment these tests https://github.com/apearson/southern-company-api/blob/5ef4712bd0ef14f8649df371925a59cf8c4b4ee7/tests/data-single.test.ts#L23 https://github.com/apearson/southern-company-api/blob/5ef4712bd0ef14f8649df371925a59cf8c4b4ee7/tests/data-multiple.test.ts#L23 https://github.com/apearson/southern-company-api/blob/5ef4712bd0ef14f8649df371925a59cf8c4b4ee7/tests/data.test.ts#L35
- setup your `.env`
- run `npm run test`

Let me know if you would like to help test and if you need any help with these steps

- Andrew

**Comment by apearson** [comment]
Closing for now
