### ISSUE TITLE
Auth mechanism changed?

### ISSUE THREAD

**Issue by andreifinski** [apearson/southern-company-api#41]
Made it working within Home Assistant a week ago, but suddenly it started throwing these errors from yesterday:
```
/node_modules/southern-company-api/dist/main.js:166
                    throw new Error(`Failed to get secondary ScWebToken: Could not find any token matches in headers`);
```

I think something has changed within auth model: either JWT acquiring mechanism or the way that cookies are used for it

**Comment by Lash-L** [comment]
Yep - I'm working on a python implementation of this api: https://github.com/Lash-L/southern_company_api

Sometime last night/ this morning they changed it.
Changing ScWebToken to SouthernJwtCookie will resolve the problem.

**Comment by apearson** [comment]
@Lash-L @andreifinski, 2.2.2 is now published with the changed auth

**Comment by apearson** [comment]
Let me know if the fix worked or didn't work

**Comment by andreifinski** [comment]
it did, thanks!
