### ISSUE TITLE
Usage no longer takes "AccountNumber"

### ISSUE THREAD

**Issue by Lash-L** [apearson/southern-company-api#55]
My python implementation of the api failed, and after some testing, it seems that usage no longer takes AccountNumber as a param. I'd double check me, but removing that fixed some issues.

**Comment by apearson** [comment]
Unfortunately, the changes are more than just a url change.  

I'm working on a fix but it'll take a little bit. 

Thank you for bring this up

**Comment by Lash-L** [comment]
Interesting - what other issues are you running in to? My python version has been working surprisingly well the past few days for myself (GPC), but a user with APC has been having some issues, curious if they line up.

**Comment by apearson** [comment]
Really the two largest issues are:

1) The URL requires the company as a query param, so I had to thread the company into the method 
2) The return data structure is completely different and requires me to rewrite most of the `getMonthlyData` code

**Comment by Lash-L** [comment]
2. Yeah - their data was all kinds of crazy for my get monthly data.

But also their hourly data is null. Do you have something similar on your side?

**Comment by apearson** [comment]
Rewrote getMonthlyData and published 3.0.0
